<#
.SYNOPSIS
    Send current PC time to DE2-115 serial clock display.

.DESCRIPTION
    Two modes:
    1. COMPILE-AND-PROGRAM (default): Generates time_init.v with current
       PC time, compiles serial_clock, and programs via USB-Blaster.
       Works with just the JTAG cable — no serial cable needed.
    2. SERIAL (requires -Serial): Sends current time over RS-232
       at 115200 baud via COM port (requires DB9 cable or USB-UART adapter).

.PARAMETER Serial
    Use RS-232 serial transmission instead of compile/program.

.PARAMETER ComPort
    COM port for serial mode (default: COM1).

.PARAMETER Loop
    Continuously update every minute (compile mode) or every second (serial mode).

.PARAMETER QuartusDir
    Quartus II installation directory (default: C:\altera\10.0\quartus).

.EXAMPLE
    .\send-time.ps1                       # Compile + program current time
    .\send-time.ps1 -Loop                 # Update every minute
    .\send-time.ps1 -Serial -ComPort COM3 # Send via serial
#>
param(
    [switch]$Serial,
    [string]$ComPort = "COM1",
    [switch]$Loop,
    [string]$QuartusDir = "C:\altera\10.0\quartus"
)

$ErrorActionPreference = "Stop"
$ProjectDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$QuartusBin = "$QuartusDir\bin"

function Get-TimeBytes {
    $t = Get-Date
    return @(
        [byte]0xAA,            # header
        [byte]$t.Hour,         # hours (0-23)
        [byte]$t.Minute,       # minutes (0-59)
        [byte]$t.Second        # seconds (0-59)
    )
}

function Write-TimeInit {
    param([datetime]$t)
    # PowerShell backtick (`) is the escape char — double it to emit a literal backtick
    $lines = @(
        '// time_init.v — auto-generated by send-time.ps1'
        '// Compile-time initial clock value.'
        '// Delete this file to fall back to defaults (00:00:00).'
        "``define INIT_HOUR   $($t.Hour)"
        "``define INIT_MINUTE $($t.Minute)"
        "``define INIT_SECOND $($t.Second)"
    )
    $path = Join-Path $ProjectDir "time_init.v"
    Set-Content -Path $path -Value ($lines -join "`r`n") -NoNewline
    Write-Host "  time_init.v → $($t.ToString('HH:mm:ss'))" -ForegroundColor Green
}

function Invoke-CompileAndProgram {
    Write-Host "── Compiling serial_clock ──" -ForegroundColor Cyan
    $proc = Start-Process -FilePath "$QuartusBin\quartus_sh.exe" -ArgumentList "--flow compile serial_clock" `
        -WorkingDirectory $ProjectDir -NoNewWindow -Wait -PassThru
    if ($proc.ExitCode -ne 0) {
        Write-Host "✘ Compile failed (exit $($proc.ExitCode))" -ForegroundColor Red
        return $false
    }
    Write-Host "  ✔ Compile OK" -ForegroundColor Green

    Write-Host "── Programming DE2-115 ──" -ForegroundColor Cyan
    $proc = Start-Process -FilePath "$QuartusBin\quartus_pgm.exe" `
        -ArgumentList "-c `"USB-Blaster [USB-0]`" -m JTAG -o `"p;output_files\serial_clock.sof`"" `
        -WorkingDirectory $ProjectDir -NoNewWindow -Wait -PassThru
    if ($proc.ExitCode -ne 0) {
        Write-Host "✘ Program failed (exit $($proc.ExitCode))" -ForegroundColor Red
        return $false
    }
    Write-Host "  ✔ Program OK  →  Time: $((Get-Date).ToString('HH:mm:ss')) on HEX5..HEX0" -ForegroundColor Green
    return $true
}

function Invoke-SerialSend {
    param([string]$port)
    try {
        $sp = New-Object System.IO.Ports.SerialPort $port, 115200, None, 8, One
        $sp.Open()
        $bytes = Get-TimeBytes
        $sp.Write($bytes, 0, 4)
        $sp.Close()
        Write-Host "  → Sent $($bytes[1]):$($bytes[2]):$($bytes[3]) via $port" -ForegroundColor Green
        return $true
    } catch {
        Write-Host "  ✘ Serial error on $port : $_" -ForegroundColor Red
        return $false
    }
}

# ── MAIN ───────────────────────────────────────────────────
Write-Host "╔══════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "║  DE2-115 Clock Update — send-time.ps1   ║" -ForegroundColor Cyan
Write-Host "╚══════════════════════════════════════════╝" -ForegroundColor Cyan

if ($Serial) {
    # ── Serial mode ──
    do {
        Write-Host "$(Get-Date -Format 'HH:mm:ss') Sending time → $ComPort ..."
        Invoke-SerialSend -port $ComPort | Out-Null
        if ($Loop) { Start-Sleep -Seconds 1 }
    } while ($Loop)
} else {
    # ── Compile-and-Program mode (default) ──
    do {
        Write-TimeInit -t (Get-Date)
        Invoke-CompileAndProgram | Out-Null
        if ($Loop) {
            Write-Host "  Next update in 60 seconds... (Ctrl+C to stop)" -ForegroundColor Yellow
            Start-Sleep -Seconds 60
        }
    } while ($Loop)
}

Write-Host "Done." -ForegroundColor Green
