// ============================================================
//  serial_clock.v — DE2-115 PC-Time Clock via UART
//
//  Displays 12-hour HH:MM:SS with AM/PM on all 8 HEX digits:
//    HEX7,HEX6 = HH (12-hour, leading zero blanked)
//    HEX5,HEX4 = MM (minutes)
//    HEX3,HEX2 = SS (seconds)
//    HEX1      = A (AM) / P (PM)
//    HEX0      = blank
//
//  INITIAL TIME via time_init.v (auto-generated by send-time.ps1):
//    `INIT_HOUR, `INIT_MINUTE, `INIT_SECOND  (24-hour format, default 0)
//
//  UART-RECEIVE via RS-232 at 115200 baud 8N1:
//    Send 4 bytes: 0xAA  HH  MM  SS
//    where HH=0-23, MM=0-59, SS=0-59 (24-hour binary)
//    Updates display immediately.
//
//  Between UART frames the clock keeps running via its
//  internal 1-second tick from the 50 MHz oscillator.
//  KEY0 resets to 00:00:00 (24-hour).
//
//  KEY3 → UART TX: pressing KEY[3] transmits byte 0xBB at 115200 baud
//  on the RS-232 TX line.  Connect to PC serial port and run:
//    .\listen-key.ps1 -ComPort <port>
//  to simulate a Windows key press on every FPGA button press.
// ============================================================

`include "time_init.v"

module serial_clock (
    input  clk,          // 50 MHz (PIN_Y2)
    input  rst_n,        // KEY0 (active-low, PIN_M23)
    input  uart_rx,      // UART RXD (PIN_G12)
    input  key3,         // KEY3 (active-low, PIN_R24) → sends Win key via UART TX
    output uart_tx,      // UART TXD (PIN_G14)
    output reg led_key3, // LEDG[0] (PIN_E21) — blinks 250ms on KEY3 press
    output [6:0] hex7,   // hour12 tens  (blank/1)
    output [6:0] hex6,   // hour12 ones  (0-9)
    output [6:0] hex5,   // minutes tens (0-5)
    output [6:0] hex4,   // minutes ones (0-9)
    output [6:0] hex3,   // seconds tens (0-5)
    output [6:0] hex2,   // seconds ones (0-9)
    output [6:0] hex1,   // A=AM / P=PM
    output [6:0] hex0    // blank
);

    // ============================================================
    //  1. 1-second tick from 50 MHz
    // ============================================================
    localparam TICK_1S = 26'd50_000_000;
    reg [25:0] tick_cnt;
    wire t_1s = (tick_cnt == TICK_1S - 1);

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n)          tick_cnt <= 0;
        else if (t_1s)       tick_cnt <= 0;
        else                 tick_cnt <= tick_cnt + 26'd1;
    end

    // ============================================================
    //  2. UART receiver — 115200 baud, 8N1
    //     Baud divider: 50,000,000 / 115,200 ≈ 434
    // ============================================================
    localparam BAUD_DIV   = 9'd434;
    localparam BAUD_HALF  = 9'd217;

    reg        rx_sync, rx_prev;
    reg [1:0]  rx_state;
    reg [8:0]  rx_baud_cnt;
    reg [2:0]  rx_bit_idx;
    reg [7:0]  rx_shift;
    reg        rx_byte_valid;
    reg [7:0]  rx_byte;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            rx_sync        <= 1'b1;
            rx_prev        <= 1'b1;
            rx_state       <= 0;
            rx_baud_cnt    <= 0;
            rx_bit_idx     <= 0;
            rx_shift       <= 0;
            rx_byte_valid  <= 1'b0;
            rx_byte        <= 0;
        end else begin
            rx_byte_valid <= 1'b0;
            rx_prev <= rx_sync;
            rx_sync <= uart_rx;

            case (rx_state)
                0: begin
                    if (rx_prev && !rx_sync) begin
                        rx_state    <= 1;
                        rx_baud_cnt <= 0;
                        rx_bit_idx  <= 0;
                    end
                end
                1: begin
                    if (rx_baud_cnt == BAUD_HALF) begin
                        if (!rx_sync) begin
                            rx_state    <= 2;
                            rx_baud_cnt <= 0;
                        end else begin
                            rx_state    <= 0;
                        end
                    end else begin
                        rx_baud_cnt <= rx_baud_cnt + 9'd1;
                    end
                end
                2: begin
                    if (rx_baud_cnt == BAUD_DIV) begin
                        rx_shift[rx_bit_idx] <= rx_sync;
                        rx_baud_cnt <= 0;
                        if (rx_bit_idx == 3'd7) begin
                            rx_state <= 3;
                        end else begin
                            rx_bit_idx <= rx_bit_idx + 3'd1;
                        end
                    end else begin
                        rx_baud_cnt <= rx_baud_cnt + 9'd1;
                    end
                end
                3: begin
                    if (rx_baud_cnt == BAUD_DIV) begin
                        rx_state <= 0;
                        rx_baud_cnt <= 0;
                        if (rx_sync) begin
                            rx_byte       <= rx_shift;
                            rx_byte_valid <= 1'b1;
                        end
                    end else begin
                        rx_baud_cnt <= rx_baud_cnt + 9'd1;
                    end
                end
            endcase
        end
    end

    // ============================================================
    //  3. Time frame parser  –  0xAA HH MM SS
    // ============================================================
    reg [1:0]  frm_state;
    reg [7:0]  frm_hour, frm_min, frm_sec;
    reg        time_update;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            frm_state   <= 0;
            frm_hour    <= 0;
            frm_min     <= 0;
            frm_sec     <= 0;
            time_update <= 1'b0;
        end else begin
            time_update <= 1'b0;
            if (rx_byte_valid) begin
                case (frm_state)
                    0: begin
                        if (rx_byte == 8'hAA) frm_state <= 1;
                    end
                    1: begin
                        if (rx_byte <= 8'd23) begin
                            frm_hour  <= rx_byte;
                            frm_state <= 2;
                        end else frm_state <= 0;
                    end
                    2: begin
                        if (rx_byte <= 8'd59) begin
                            frm_min   <= rx_byte;
                            frm_state <= 3;
                        end else frm_state <= 0;
                    end
                    3: begin
                        if (rx_byte <= 8'd59) begin
                            frm_sec    <= rx_byte;
                            time_update <= 1'b1;
                        end
                        frm_state <= 0;
                    end
                endcase
            end
        end
    end

    // ============================================================
    //  4. Time counter (24-hour, free-running with 1-second tick)
    // ============================================================
    reg [3:0] hr1, hr0;     // hours tens/ones   (BCD 24h: 0-2, 0-9)
    reg [3:0] min1, min0;   // minutes tens/ones (BCD: 0-5, 0-9)
    reg [3:0] sec1, sec0;   // seconds tens/ones (BCD: 0-5, 0-9)

    wire carry_sec0 = t_1s && (sec0 == 4'd9);
    wire carry_sec1 = carry_sec0 && (sec1 == 4'd5);
    wire carry_min0 = carry_sec1 && (min0 == 4'd9);
    wire carry_min1 = carry_min0 && (min1 == 4'd5);
    wire is_23h59m  = (hr1 == 4'd2) && (hr0 == 4'd3);

    `ifndef INIT_HOUR
        `define INIT_HOUR    0
        `define INIT_MINUTE  0
        `define INIT_SECOND  0
    `endif

    wire [3:0] init_h1  = `INIT_HOUR   / 4'd10;
    wire [3:0] init_h0  = `INIT_HOUR   % 4'd10;
    wire [3:0] init_m1  = `INIT_MINUTE / 4'd10;
    wire [3:0] init_m0  = `INIT_MINUTE % 4'd10;
    wire [3:0] init_s1  = `INIT_SECOND / 4'd10;
    wire [3:0] init_s0  = `INIT_SECOND % 4'd10;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            {hr1, hr0, min1, min0, sec1, sec0} <= {init_h1, init_h0, init_m1, init_m0, init_s1, init_s0};
        end else if (time_update) begin
            hr1  <= frm_hour  / 4'd10;
            hr0  <= frm_hour  % 4'd10;
            min1 <= frm_min   / 4'd10;
            min0 <= frm_min   % 4'd10;
            sec1 <= frm_sec   / 4'd10;
            sec0 <= frm_sec   % 4'd10;
        end else begin
            if (t_1s)          sec0 <= (sec0 == 4'd9) ? 4'd0 : sec0 + 4'd1;
            if (carry_sec0)    sec1 <= (sec1 == 4'd5) ? 4'd0 : sec1 + 4'd1;
            if (carry_sec1)    min0 <= (min0 == 4'd9) ? 4'd0 : min0 + 4'd1;
            if (carry_min0)    min1 <= (min1 == 4'd5) ? 4'd0 : min1 + 4'd1;
            if (carry_min1) begin
                if (is_23h59m)      {hr1, hr0} <= {4'd0, 4'd0};
                else if (hr0 == 9)  {hr1, hr0} <= {hr1 + 4'd1, 4'd0};
                else                hr0 <= hr0 + 4'd1;
            end
        end
    end

    // ============================================================
    //  5. 24-hour → 12-hour conversion + AM/PM
    // ============================================================
    //  hour24 = hr1*10 + hr0   (0-23)
    //  hour12 = hour24 % 12;  if hour12==0 then hour12=12
    //  is_pm  = hour24 >= 12

    wire [4:0] hour24 = hr1 * 4'd10 + hr0;        // 0-23 (5 bits)
    wire [4:0] hour12_mod = hour24 % 4'd12;        // 0-11
    wire [4:0] hour12 = (hour12_mod == 0) ? 5'd12 : hour12_mod;
    wire       is_pm = (hour24 >= 5'd12);

    wire [3:0] h12_tens = hour12 / 4'd10;          // 0 or 1
    wire [3:0] h12_ones = hour12 % 4'd10;          // 0-9

    // Blank leading zero: if hour12 < 10, hex7 blank
    wire       blank_tens = (hour12 < 5'd10);

    // ============================================================
    //  6. 7-segment patterns
    // ============================================================
    //  bit order: {g, f, e, d, c, b, a}  active-low (0=ON)
    function [6:0] seg7(input [3:0] v);
        case (v)
            4'd0: seg7 = 7'b1000000;
            4'd1: seg7 = 7'b1111001;
            4'd2: seg7 = 7'b0100100;
            4'd3: seg7 = 7'b0110000;
            4'd4: seg7 = 7'b0011001;
            4'd5: seg7 = 7'b0010010;
            4'd6: seg7 = 7'b0000010;
            4'd7: seg7 = 7'b1111000;
            4'd8: seg7 = 7'b0000000;
            4'd9: seg7 = 7'b0010000;
            default: seg7 = 7'b1111111;
        endcase
    endfunction

    // Letter patterns for AM/PM display
    //  "A": segments a,b,c,e,f,g = 0 0 0 1 0 0 0 → 7'b0001000
    //  "P": segments a,b,e,f,g     = 0 0 0 1 1 0 0 → 7'b0001100
    localparam SEG_A = 7'b0001000;
    localparam SEG_P = 7'b0001100;
    localparam SEG_BLANK = 7'b1111111;

    // ============================================================
    //  7. Assign all 8 HEX outputs
    // ============================================================
    assign hex7 = blank_tens ? SEG_BLANK : seg7(h12_tens);
    assign hex6 = seg7(h12_ones);
    assign hex5 = seg7(min1);
    assign hex4 = seg7(min0);
    assign hex3 = seg7(sec1);
    assign hex2 = seg7(sec0);
    assign hex1 = is_pm ? SEG_P : SEG_A;
    assign hex0 = SEG_BLANK;

    // ============================================================
    //  8. KEY3 debouncer
    //     KEY[3] on DE2-115 is active-low; debounce for ~10ms
    // ============================================================
    localparam DB_CNT_MAX = 20'd500_000;  // 10 ms @ 50 MHz
    reg [19:0] db_cnt;
    reg        db_key3, db_key3_prev, key3_sync;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            db_cnt      <= 0;
            db_key3     <= 1'b1;
            db_key3_prev <= 1'b1;
            key3_sync   <= 1'b1;
        end else begin
            db_key3_prev <= db_key3;
            key3_sync    <= key3;

            // Debounce: wait for stable low for DB_CNT_MAX cycles
            if (key3_sync != db_key3) begin
                if (db_cnt == DB_CNT_MAX) begin
                    db_key3 <= key3_sync;
                    db_cnt  <= 0;
                end else begin
                    db_cnt <= db_cnt + 20'd1;
                end
            end else begin
                db_cnt <= 0;
            end
        end
    end

    // Falling edge on db_key3 (active-low: 1→0 = press)
    wire key3_press = db_key3_prev && !db_key3;

    // ============================================================
    //  9. UART transmitter — 115200 baud, 8N1
    //     Sends key byte 0xBB when KEY3 is pressed
    // ============================================================
    localparam TX_CMD = 8'hBB;

    reg [1:0]  tx_state;
    reg [8:0]  tx_baud_cnt;
    reg [3:0]  tx_bit_idx;
    reg [7:0]  tx_shift;
    reg        tx_busy;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            tx_state    <= 0;
            tx_baud_cnt <= 0;
            tx_bit_idx  <= 0;
            tx_shift    <= TX_CMD;
            tx_busy     <= 1'b0;
        end else begin
            case (tx_state)
                0: begin
                    // Wait for KEY3 press or idle
                    if (key3_press && !tx_busy) begin
                        tx_shift   <= TX_CMD;
                        tx_state   <= 1;
                        tx_baud_cnt <= 0;
                        tx_bit_idx <= 0;
                        tx_busy    <= 1'b1;
                    end
                end
                1: begin
                    // Start bit (low)
                    if (tx_baud_cnt == BAUD_DIV) begin
                        tx_baud_cnt <= 0;
                        tx_state    <= 2;
                    end else begin
                        tx_baud_cnt <= tx_baud_cnt + 9'd1;
                    end
                end
                2: begin
                    // Data bits (LSB first)
                    if (tx_baud_cnt == BAUD_DIV) begin
                        tx_baud_cnt <= 0;
                        tx_shift    <= {1'b0, tx_shift[7:1]};
                        if (tx_bit_idx == 4'd7) begin
                            tx_state <= 3;
                        end else begin
                            tx_bit_idx <= tx_bit_idx + 4'd1;
                        end
                    end else begin
                        tx_baud_cnt <= tx_baud_cnt + 9'd1;
                    end
                end
                3: begin
                    // Stop bit (high)
                    if (tx_baud_cnt == BAUD_DIV) begin
                        tx_baud_cnt <= 0;
                        tx_state    <= 0;
                        tx_busy     <= 1'b0;
                    end else begin
                        tx_baud_cnt <= tx_baud_cnt + 9'd1;
                    end
                end
            endcase
        end
    end

    // TX output: idle high, start low, data LSB-first, stop high
    reg tx_out;
    always @(*) begin
        case (tx_state)
            0:      tx_out = 1'b1;     // idle
            1:      tx_out = 1'b0;     // start bit
            2:      tx_out = tx_shift[0];  // LSB first
            3:      tx_out = 1'b1;     // stop bit
            default: tx_out = 1'b1;
        endcase
    end
    assign uart_tx = tx_out;

    // ============================================================
    //  10. KEY3 LED one-shot — blinks LEDG[0] for ~250ms on press
    // ============================================================
    localparam LED_MS250 = 24'd12_500_000;   // 250 ms @ 50 MHz
    reg [23:0] led_cnt;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            led_key3 <= 1'b0;
            led_cnt  <= 0;
        end else begin
            if (key3_press) begin
                led_key3 <= 1'b1;
                led_cnt  <= 0;
            end else if (led_key3) begin
                if (led_cnt == LED_MS250) begin
                    led_key3 <= 1'b0;
                    led_cnt  <= 0;
                end else begin
                    led_cnt <= led_cnt + 24'd1;
                end
            end
        end
    end

endmodule
