// ============================================================
//  serial_clock.v — DE2-115 PC-Time Clock via UART
//
//  Displays HH:MM:SS on HEX5..HEX0:
//    HEX5,HEX4 = HH (hours)   → 00-23
//    HEX3,HEX2 = MM (minutes) → 00-59
//    HEX1,HEX0 = SS (seconds) → 00-59
//
//  INITIAL TIME via time_init.v (auto-generated by send-time.ps1):
//    `INIT_HOUR, `INIT_MINUTE, `INIT_SECOND  (default 0)
//
//  UART-RECEIVE via RS-232 at 115200 baud 8N1:
//    Send 4 bytes: 0xAA  HH  MM  SS
//    where HH=0-23, MM=0-59, SS=0-59 (binary)
//    Updates display immediately, resets tick counter.
//
//  Between UART frames the clock keeps running via its
//  internal 1-second tick from the 50 MHz oscillator.
//  KEY0 resets to 00:00:00.
// ============================================================

`include "time_init.v"

module serial_clock (
    input  clk,          // 50 MHz (PIN_Y2)
    input  rst_n,        // KEY0 (active-low, PIN_M23)
    input  uart_rx,      // UART RXD (PIN_G12)
    output [6:0] hex5,   // hours tens    (0-2)
    output [6:0] hex4,   // hours ones    (0-9)
    output [6:0] hex3,   // minutes tens  (0-5)
    output [6:0] hex2,   // minutes ones  (0-9)
    output [6:0] hex1,   // seconds tens  (0-5)
    output [6:0] hex0    // seconds ones  (0-9)
);

    // ============================================================
    //  1. 1-second tick from 50 MHz
    // ============================================================
    localparam TICK_1S = 26'd50_000_000;
    reg [25:0] tick_cnt;
    wire t_1s = (tick_cnt == TICK_1S - 1);

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n)          tick_cnt <= 0;
        else if (t_1s)       tick_cnt <= 0;
        else                 tick_cnt <= tick_cnt + 26'd1;
    end

    // ============================================================
    //  2. UART receiver — 115200 baud, 8N1
    //     Baud divider: 50,000,000 / 115,200 ≈ 434
    // ============================================================
    localparam BAUD_DIV   = 9'd434;
    localparam BAUD_HALF  = 9'd217;

    reg        rx_sync, rx_prev;         // synchroniser + edge detect
    reg [1:0]  rx_state;                 // IDLE=0, START=1, DATA=2, STOP=3
    reg [8:0]  rx_baud_cnt;              // baud-rate counter
    reg [2:0]  rx_bit_idx;               // bit position 0..7
    reg [7:0]  rx_shift;                 // receive shift register
    reg        rx_byte_valid;            // strobe: byte received
    reg [7:0]  rx_byte;                  // received byte

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            rx_sync        <= 1'b1;
            rx_prev        <= 1'b1;
            rx_state       <= 0;
            rx_baud_cnt    <= 0;
            rx_bit_idx     <= 0;
            rx_shift       <= 0;
            rx_byte_valid  <= 1'b0;
            rx_byte        <= 0;
        end else begin
            rx_byte_valid <= 1'b0;   // default: single-cycle strobe

            // synchronise async UART input
            rx_prev <= rx_sync;
            rx_sync <= uart_rx;

            case (rx_state)
                0: begin // IDLE — wait for start bit (falling edge)
                    if (rx_prev && !rx_sync) begin
                        rx_state    <= 1;  // START
                        rx_baud_cnt <= 0;
                        rx_bit_idx  <= 0;
                    end
                end

                1: begin // START — sample middle of start bit
                    if (rx_baud_cnt == BAUD_HALF) begin
                        if (!rx_sync) begin           // valid start
                            rx_state    <= 2;         // DATA
                            rx_baud_cnt <= 0;
                        end else begin
                            rx_state    <= 0;         // glitch → IDLE
                        end
                    end else begin
                        rx_baud_cnt <= rx_baud_cnt + 9'd1;
                    end
                end

                2: begin // DATA — receive 8 bits LSB first
                    if (rx_baud_cnt == BAUD_DIV) begin
                        rx_shift[rx_bit_idx] <= rx_sync;
                        rx_baud_cnt <= 0;
                        if (rx_bit_idx == 3'd7) begin
                            rx_state <= 3;            // STOP
                        end else begin
                            rx_bit_idx <= rx_bit_idx + 3'd1;
                        end
                    end else begin
                        rx_baud_cnt <= rx_baud_cnt + 9'd1;
                    end
                end

                3: begin // STOP — verify stop bit is high
                    if (rx_baud_cnt == BAUD_DIV) begin
                        rx_state <= 0;                // back to IDLE
                        rx_baud_cnt <= 0;
                        if (rx_sync) begin            // valid stop bit
                            rx_byte       <= rx_shift;
                            rx_byte_valid <= 1'b1;
                        end
                        // framing error: stop bit low → discard silently
                    end else begin
                        rx_baud_cnt <= rx_baud_cnt + 9'd1;
                    end
                end
            endcase
        end
    end

    // ============================================================
    //  3. Time frame parser
    //     Protocol: 0xAA HH MM SS  (4 bytes)
    // ============================================================
    reg [1:0]  frm_state;         // 0=WAIT_HEADER, 1=HOUR, 2=MIN, 3=SEC
    reg [7:0]  frm_hour, frm_min, frm_sec;
    reg        time_update;       // strobe: update time from frame

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            frm_state   <= 0;
            frm_hour    <= 0;
            frm_min     <= 0;
            frm_sec     <= 0;
            time_update <= 1'b0;
        end else begin
            time_update <= 1'b0;

            if (rx_byte_valid) begin
                case (frm_state)
                    0: begin                         // WAIT_HEADER
                        if (rx_byte == 8'hAA) begin
                            frm_state <= 1;          // expect HOUR next
                        end
                        // else stay in WAIT_HEADER (auto-resync)
                    end
                    1: begin                         // HOUR
                        if (rx_byte <= 8'd23) begin
                            frm_hour   <= rx_byte;
                            frm_state  <= 2;         // expect MIN next
                        end else begin
                            frm_state  <= 0;         // invalid → resync
                        end
                    end
                    2: begin                         // MINUTE
                        if (rx_byte <= 8'd59) begin
                            frm_min    <= rx_byte;
                            frm_state  <= 3;         // expect SEC next
                        end else begin
                            frm_state  <= 0;         // invalid → resync
                        end
                    end
                    3: begin                         // SECOND
                        if (rx_byte <= 8'd59) begin
                            frm_sec    <= rx_byte;
                            time_update <= 1'b1;     // complete frame
                        end
                        frm_state <= 0;              // back to WAIT_HEADER
                    end
                endcase
            end
        end
    end

    // ============================================================
    //  4. Time counter (free-running with 1-second tick,
    //     overridden by UART frame updates)
    // ============================================================
    reg [3:0] hr1, hr0;     // hours tens/ones   (BCD: 0-2, 0-9)
    reg [3:0] min1, min0;   // minutes tens/ones (BCD: 0-5, 0-9)
    reg [3:0] sec1, sec0;   // seconds tens/ones (BCD: 0-5, 0-9)

    // carry chain
    wire carry_sec0 = t_1s && (sec0 == 4'd9);
    wire carry_sec1 = carry_sec0 && (sec1 == 4'd5);
    wire carry_min0 = carry_sec1 && (min0 == 4'd9);
    wire carry_min1 = carry_min0 && (min1 == 4'd5);
    wire is_23h59m  = (hr1 == 4'd2) && (hr0 == 4'd3);

    // Compile-time initial time from time_init.v (default 00:00:00)
    // Can be overridden by UART frame after programming.
    `ifndef INIT_HOUR
        `define INIT_HOUR    0
        `define INIT_MINUTE  0
        `define INIT_SECOND  0
    `endif

    wire [3:0] init_h1  = `INIT_HOUR   / 4'd10;
    wire [3:0] init_h0  = `INIT_HOUR   % 4'd10;
    wire [3:0] init_m1  = `INIT_MINUTE / 4'd10;
    wire [3:0] init_m0  = `INIT_MINUTE % 4'd10;
    wire [3:0] init_s1  = `INIT_SECOND / 4'd10;
    wire [3:0] init_s0  = `INIT_SECOND % 4'd10;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            // Set to compile-time initial time from PC when script ran
            {hr1, hr0, min1, min0, sec1, sec0} <= {init_h1, init_h0, init_m1, init_m0, init_s1, init_s0};
        end else if (time_update) begin
            // Override from UART frame: convert binary → BCD
            hr1  <= frm_hour  / 4'd10;
            hr0  <= frm_hour  % 4'd10;
            min1 <= frm_min   / 4'd10;
            min0 <= frm_min   % 4'd10;
            sec1 <= frm_sec   / 4'd10;
            sec0 <= frm_sec   % 4'd10;
        end else begin
            // ── sec0 ──
            if (t_1s) sec0 <= (sec0 == 4'd9) ? 4'd0 : sec0 + 4'd1;

            // ── sec1 ──
            if (carry_sec0) sec1 <= (sec1 == 4'd5) ? 4'd0 : sec1 + 4'd1;

            // ── min0 ──
            if (carry_sec1) min0 <= (min0 == 4'd9) ? 4'd0 : min0 + 4'd1;

            // ── min1 ──
            if (carry_min0) min1 <= (min1 == 4'd5) ? 4'd0 : min1 + 4'd1;

            // ── hours (wrap at 23:59:59 → 00:00:00) ──
            if (carry_min1) begin
                if (is_23h59m) begin
                    hr1 <= 4'd0;
                    hr0 <= 4'd0;
                end else if (hr0 == 4'd9) begin
                    hr0 <= 4'd0;
                    hr1 <= hr1 + 4'd1;
                end else begin
                    hr0 <= hr0 + 4'd1;
                end
            end
        end
    end

    // ============================================================
    //  5. 7-segment decoders (active-low, common anode)
    //     bit order: {g, f, e, d, c, b, a}
    // ============================================================
    function [6:0] seg7(input [3:0] v);
        case (v)
            4'd0: seg7 = 7'b1000000;
            4'd1: seg7 = 7'b1111001;
            4'd2: seg7 = 7'b0100100;
            4'd3: seg7 = 7'b0110000;
            4'd4: seg7 = 7'b0011001;
            4'd5: seg7 = 7'b0010010;
            4'd6: seg7 = 7'b0000010;
            4'd7: seg7 = 7'b1111000;
            4'd8: seg7 = 7'b0000000;
            4'd9: seg7 = 7'b0010000;
            default: seg7 = 7'b1111111;
        endcase
    endfunction

    assign hex5 = seg7(hr1);
    assign hex4 = seg7(hr0);
    assign hex3 = seg7(min1);
    assign hex2 = seg7(min0);
    assign hex1 = seg7(sec1);
    assign hex0 = seg7(sec0);

endmodule
